### ISSUE TITLE
Post your YAML plugins here!

### ISSUE THREAD

**Issue by maurermj08** [maurermj08/efetch#11]
If you created a YAML plugin and are willing to share it, please post it here in the comments! I will add them to the [YAML Plugins](https://github.com/maurermj08/efetch/wiki/YAML-Plugins/). A simple plain text post is fine with a description and any dependencies. 

Example:
CLAMSCAN: Runs ClamAV against a specific file and displays the results.
Requires: clamav

```
clamscan:
  name: Clam Scan
  icon: fa-bug
  command: "clamscan '{{ file_cache_path }}'"
```
